wandb_version: 1

learning_rate:
  desc: null
  value: 100000.0
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702340406.83521
    t:
      1:
      - 1
      - 30
      - 55
      - 76
      - 77
      3:
      - 16
      - 23
      4: 3.10.5
      5: 0.16.1
      8:
      - 5
      13: darwin-arm64
